taxi_rides_ny:
  outputs:
    dev:
      dbname: dtc_zoomcamp_2025
      host: localhost
      pass: password
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
